config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :tasks do
      member do
        patch :completed
      end
    end
  end
  root "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :tasks, dependent: :delete_all
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  def completed?
    !completed_at.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all

    @q = Project.ransack(params[:q])
    @projects = @q.result(distinct: true)
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    @project.tasks.clear     
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    ["title"]
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action :set_project 
	before_action :set_task, except: [:create]

	def create
		@task = @project.tasks.create(task_params)
		redirect_to @project
	end 

	def destroy
		if @task.destroy
			flash[:success] = "Task was deleted successfully"
		else
			flash[:error] = "Task was not deleted"
		end
		redirect_to @project
	end

	def completed
		@task.update_attribute(:completed_at, Time.now)
		redirect_to @project, notice: 'task was completed successfully'
	end

	private

	def set_project
		@project = Project.find(params[:project_id])
	end

	def set_task
		@task = @project.tasks.find(params[:id])
	end

	def task_params
		params[:task].permit(:content)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cms</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'true' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'true' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<%= search_form_for @q do |f| %>
  <%= f.label :title_cont %>
  <%= f.search_field :title_cont, autofocus: 'true', autocomplete: 'true' %>
<% end %>

<%= link_to 'Clear search', request.path if request.query_parameters.any? %>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<div class="col-md-8">
  <%= render @project.tasks %>
  <div class="form-group">
    <%= render 'tasks/form'%>
  </div>
</div>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %> |
<%= link_to 'Delete', project_path(@project), method: :delete, data: {confirm: 'are you sure?'}  %>

app/views/tasks/_form.html.erb
<div style="margin: 10px 0">
	<%= form_for([@project, @project.tasks.build]) do |f| %>
		<%= f.text_field :content %>
		<%= f.submit %>
	<% end  %>
</div>

app/views/tasks/_task.html.erb
<P><%= task.content %></P> 
<span>
	<%= link_to project_task_path(@project, task.id), method: :delete, data:{confirm: 'are you sure?'} do %>
		<i class='fa fa-trash-can'></i>
	<% end %>
</span>
<span>
<%= link_to completed_project_task_path(@project, task.id), method: :patch do %>
	<i class='fa fa-check'></i>
<% end %>
</span>